name: Build nanoutimes node binding

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: josepharhar/nanoutimes
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - id: artifact-name
        run: |
          echo "name=$(node -p '`node-v${process.versions.modules}-darwin-${os.arch()}`')" >> "$GITHUB_OUTPUT"
      - run: |
          npm install -g node-gyp
          node-gyp configure && node-gyp build
          mkdir -p "artifact/${{ steps.artifact-name.outputs.name }}"
          mv build/Release/nanoutimes.node "artifact/${{ steps.artifact-name.outputs.name }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: artifact
