name: Build nanoutimes node binding

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: josepharhar/nanoutimes
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.0
      - id: artifact-name
        run: |
          echo "name=$(node -p '`node-v${process.versions.modules}-darwin-${os.arch()}`')" >> "$GITHUB_OUTPUT"
      - run: |
          npm install -g node-gyp
          node-gyp configure && node-gyp build
          mkdir -p "artifact/${{ steps.artifact-name.outputs.name }}"
          mv build/Release/nanoutimes.node "artifact/${{ steps.artifact-name.outputs.name }}"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: artifact
