name: Build nanoutimes node binding

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: josepharhar/nanoutimes
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24.10.0
      - id: artifact-name
        run: |
          echo "name=$(node -p '`node-v${process.versions.modules}-darwin-${os.arch()}`')" >> "$GITHUB_OUTPUT"
      - run: |
          npm install -g node-gyp
          node-gyp configure && node-gyp build
          mkdir -p "artifact/${{ steps.artifact-name.outputs.name }}"
          mv build/Release/nanoutimes.node "artifact/${{ steps.artifact-name.outputs.name }}"
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: artifact
